name: Build and Push Docker Image
run-name: ${{ gitea.actor }} is runs ci pipeline
on: [ push ]

env:
  IMAGE_NAME: "scraper_magnit_ru"

jobs:

  publish:
    runs-on: ubuntu-latest

    container:
      image: catthehacker/ubuntu:act-latest
    if: gitea.ref == 'refs/heads/main'
    steps:
      -
        name: Login to registry
        uses: https://github.com/docker/login-action@v3
        with:
          registry: registry.int.belfood.by
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}
      - uses: https://github.com/actions/checkout@v4
      - name: Set up Docker Buildx
        uses: https://github.com/docker/setup-buildx-action@v3
        with:
          driver: docker
          config-inline: |
            [registry."registry.int.belfood.by"]
              # http = true
              # insecure = true                                    
      - name: Build and push Docker image
        uses: https://github.com/docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "registry.int.belfood.by/${{ env.IMAGE_NAME }}:${{gitea.sha}},registry.int.belfood.by/${{ env.IMAGE_NAME }}:latest"